### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by xiaoyang666** [ORNL-Modelica/UnrealEngine-FMIPlugin#10]
Hi
This is a very good project.

Whenever I load the fmu file, there will be a crash

I am very sincerely seeking help.

![$D35U@Z3}V~V@~TE63AHRON](https://user-images.githubusercontent.com/37059168/100041904-429ae280-2e45-11eb-9da4-7d8c633c5430.png)

**Comment by xiaoyang666** [comment]
@greenwoodms06

**Comment by tnorby** [comment]
@xiaoyang666 thanks for bringing this to our attention.

It looks like we didn't add in the requisite .dlls - I have added them in. Can you check these out and let me know if this resolves your issue?

**Comment by tnorby** [comment]
@greenwoodms06 - One additional note, it looks like we get a crash when attempting to open a non-existent file. The project opens with the test.fmu from your local path. Presumably if a user picks a file and (re)moves it then tries to run there will be a crash rather than a helpful message.

**Comment by greenwoodms06** [comment]
@tnorby hmmm. Yes I think I came upon a similar crash too... was busy so I didn't think much about it at the time. Seems like we need to add some `exists()` check or something such that it fails elegantly on beginplay()

**Comment by greenwoodms06** [comment]
@tnorby I added a simple catch to hopefully catch the common situation where the extracted fmu is missing

**Comment by xiaoyang666** [comment]
Thank you very much for your help.
After the change, the running program does not flash back.

**Comment by greenwoodms06** [comment]
@xiaoyang666 are you saying it works now?

**Comment by xiaoyang666** [comment]
> @ xiaoyang666您是说现在可以使用吗？

No problem at the moment. The task I am doing now is to import the Adams model into UE4 for real-time simulation of vehicle dynamics. Create a vehicle class parent class in UE4 and let FMU as a child class. This is my current idea, I hope it will work through this plugin.

**Comment by greenwoodms06** [comment]
@xiaoyang666 Excellent. That sounds great. We would love to know how it goes or see a demo of anything you use it for. I'll go ahead and close this issue.
