### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by l0wl3vel** [ORNL-Modelica/UnrealEngine-FMIPlugin#18]
Under which license does the code in this repository stand?

**Comment by greenwoodms06** [comment]
Thank you for bringing this to our attention. We will work on submoduling, etc. 3rd party code to simplify/remove licensing issues. Likely we will then go with the Apache 2 license.

**Comment by greenwoodms06** [comment]
We have removed the third party code from being included with the project and clarified the license (#19 ). Thank you again.
