### ISSUE TITLE
try-catch in A_FMU causes packaging error

### ISSUE THREAD

**Issue by Omnicrola** [ORNL-Modelica/UnrealEngine-FMIPlugin#20]
When running in editor, the plugin will run normally.  When attempting to package for Windows desktop, the UnrealBuildTool will throw the following error and abort: 

``error C4530: C++ exception handler used, but unwind semantics are not enabled``

Commenting out the try/catch will allow the packaging process to complete, but that's obviously not the best solution.

**Comment by greenwoodms06** [comment]
Hmmm... @tnorby  or @Omnicrola do you have any insight as to why that error is occurring?

**Comment by greenwoodms06** [comment]
Alrighty... Thanks for that.

I followed a recommendation [here](https://forums.unrealengine.com/t/how-can-i-enable-unwind-semantics-for-c-style-exceptions/284934) which yields adding in a sible line in the FMIKit.build.cd file.

I will push that to the master branch.

**Comment by greenwoodms06** [comment]
I'm sure there will be other issues that arise given this is a prototype but at least we can package now! :)
