### ISSUE TITLE
Can I use this plugin for real-time multi-physics field simulation and interaction in Unreal Engine

### ISSUE THREAD

**Issue by QiHang-78** [ORNL-Modelica/UnrealEngine-FMIPlugin#25]
Currently I have implemented some multi-physics field simulation calculations in comsol, now I would like to be able to visualize and interact with such a process, can I do that with this plugin?

**Comment by greenwoodms06** [comment]
This plugin can be used to interact with FMUs. If you are able to package as an FMU then it would theoretically be possible. However, if you are looking for something to visualize data generally then this is not the right tool.  I would suggest perhaps seeing if [ParaView](https://www.paraview.org/) would better suit your purpose.

**Comment by QiHang-78** [comment]
您好，您的邮件已收到
